
version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"  # Main port for LocalStack services
      - "4510:4510"  # Port for CloudWatch Logs (optional if you want to expose it)
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_SERVICES=lambda,logs  # Add 'logs' to enable CloudWatch Logs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_DOCKER_VOLUME:-./volume}:/volume"
      - "/var/run/docker.sock:/var/run/docker.sock"

